#!/usr/bin/env python3

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: extract_postmortem_suite_smoke_test.py <extract_postmortem_suite.py>", file=sys.stderr)
        return 2

    script = Path(sys.argv[1])
    with tempfile.TemporaryDirectory() as tempdir:
        temp = Path(tempdir)
        events = temp / "events.csv"
        positions = temp / "positions.epd"
        output = temp / "focused.epd"

        events.write_text(
            "\n".join(
                [
                    "severity,categories,game,ply,uci,reference_avoid",
                    "300,engine-prefers-negative-see|played-negative-see,1,8,e4d5,true",
                    "250,equal-value-capture,2,10,a1a8,false",
                    "200,engine-can-avoid-negative-see|played-negative-see,3,12,b2b7,true",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        positions.write_text(
            "\n".join(
                [
                    "# generated by postmortem",
                    '8/8/8/3p4/4P3/8/8/4K2k w - - am e4d5; id "postmortem-0001-g1-p8"; theme "engine-prefers-negative-see|played-negative-see"; acd 5;',
                    'r6k/8/8/8/8/8/8/R6K w - - bm a1a8; id "postmortem-0002-g2-p10"; theme "equal-value-capture"; acd 5;',
                    '1r5k/1P6/8/8/8/8/8/4K3 w - - am b2b7; id "postmortem-0003-g3-p12"; theme "engine-can-avoid-negative-see|played-negative-see"; acd 5;',
                    "",
                ]
            ),
            encoding="utf-8",
        )

        completed = subprocess.run(
            [
                sys.executable,
                str(script),
                "--events",
                str(events),
                "--positions",
                str(positions),
                "--output",
                str(output),
                "--category",
                "played-negative-see",
                "--reference-avoid-only",
                "--sort",
                "severity-desc",
            ],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
            timeout=10,
        )
        if completed.returncode != 0:
            print(completed.stdout, file=sys.stderr)
            print(completed.stderr, file=sys.stderr)
            return completed.returncode

        text = output.read_text(encoding="utf-8")
        if "postmortem-0001-g1-p8" not in text or "postmortem-0003-g3-p12" not in text:
            print(f"expected selected postmortem positions in output:\n{text}", file=sys.stderr)
            return 1
        if "postmortem-0002-g2-p10" in text:
            print(f"unselected postmortem position was written:\n{text}", file=sys.stderr)
            return 1
        if text.find("postmortem-0001-g1-p8") > text.find("postmortem-0003-g3-p12"):
            print(f"expected severity-desc output order:\n{text}", file=sys.stderr)
            return 1
        if "wrote 2 postmortem positions" not in completed.stdout:
            print(f"unexpected stdout:\n{completed.stdout}", file=sys.stderr)
            return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
